## Heart disease data from GitHub

In [2]:
# 1. importing libraries
import pandas as pd

In [3]:
# 2. importing data from GitHub
heart_disease = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv")

## Describe data

In [6]:
# 3. Describing data
heart_disease.dtypes    #atribute

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [10]:
# a. Columns 
heart_disease_columns = heart_disease.columns
heart_disease_columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

In [12]:
# b. index
heart_disease.index

RangeIndex(start=0, stop=303, step=1)

In [15]:
# c. huge data analysis
heart_disease.describe()   # works only on numeric columns

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [21]:
# d. info  - index combined with dtypes
heart_disease.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [23]:
# e. mean - average number
heart_disease.mean(numeric_only=True)

age          54.366337
sex           0.683168
cp            0.966997
trestbps    131.623762
chol        246.264026
fbs           0.148515
restecg       0.528053
thalach     149.646865
exang         0.326733
oldpeak       1.039604
slope         1.399340
ca            0.729373
thal          2.313531
target        0.544554
dtype: float64

In [25]:
# f. sum
heart_disease.sum()

age         16473.0
sex           207.0
cp            293.0
trestbps    39882.0
chol        74618.0
fbs            45.0
restecg       160.0
thalach     45343.0
exang          99.0
oldpeak       315.0
slope         424.0
ca            221.0
thal          701.0
target        165.0
dtype: float64

In [28]:
# g. Summary of the row (age in this case)
heart_disease["age"].sum()

np.int64(16473)

In [4]:
# h. lenght (rows)
len(heart_disease)

303

## Viewing and Selecting data

In [10]:
# 2. Top of the data frame
heart_disease.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [9]:
# 2. Bottom of the data frame
heart_disease.tail(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1,0
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [17]:
# 3.  .loc  &  .iloc

animals = pd.Series(["cat", "dog", "snake", "panda", "bird"], index=[0, 3, 9, 8, 3])
animals

0      cat
3      dog
9    snake
8    panda
3     bird
dtype: str

In [21]:
# .loc
animals.loc[3]

3     dog
3    bird
dtype: str

In [20]:
# Gonna show all features of 4rd index [3]
heart_disease.loc[3]

age          56.0
sex           1.0
cp            1.0
trestbps    120.0
chol        236.0
fbs           0.0
restecg       1.0
thalach     178.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            0.0
thal          2.0
target        1.0
Name: 3, dtype: float64

In [26]:
# .iloc - refers to posiotion 
# pokaże to co faktycznie znajduje się na 3 indeksie (a nie gdzie my ustawiamy indexy)
heart_disease.iloc[3]

age          56.0
sex           1.0
cp            1.0
trestbps    120.0
chol        236.0
fbs           0.0
restecg       1.0
thalach     178.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            0.0
thal          2.0
target        1.0
Name: 3, dtype: float64

In [36]:
# Same as .head(4)
heart_disease.loc[:3]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1

In [43]:
# Boolean indexing
heart_disease[heart_disease["age"] == 50]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2,1
104,50,1,2,129,196,0,1,163,0,0.0,2,0,2,1
108,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
109,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
184,50,1,0,150,243,0,0,128,0,2.6,1,0,3,0
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3,0
257,50,1,0,144,200,0,0,126,1,0.9,1,0,3,0