## Introduction to pandas

In [2]:
import pandas as pd

In [13]:
# 2 main datatypes 

series = pd.Series(["BMW", "Toyota", "Honda"])

In [14]:
series

0       BMW
1    Toyota
2     Honda
dtype: str

In [16]:
# series = 1-dimensional (1 column)

In [17]:
colours = pd.Series(["Red", "Blue", "Orange"])
colours

0       Red
1      Blue
2    Orange
dtype: str

In [21]:
# Dataframe = 2-dimensional (2 and more columns)
car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make  Colour
0      BMW     Red
1   Toyota    Blue
2    Honda  Orange

In [30]:
# Importing data
car_sales = pd.read_csv("car-sales.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

1 - index column

ROW - axis = 0

COLUMN - axis = 1

In [37]:
# Exporting a dataframe
car_sales.to_csv("exported-car-sales.csv", index = False)

In [38]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")
exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [3]:
# importing data from GitHub
heart_disease = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv")

In [7]:
heart_disease.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [8]:
# This tells pandas to only find the mean/average on numerical columns
heart_disease.mean(numeric_only=True)

age          54.366337
sex           0.683168
cp            0.966997
trestbps    131.623762
chol        246.264026
fbs           0.148515
restecg       0.528053
thalach     149.646865
exang         0.326733
oldpeak       1.039604
slope         1.399340
ca            0.729373
thal          2.313531
target        0.544554
dtype: float64